### ISSUE TITLE
Doesn't build out of the box

### ISSUE THREAD

**Issue by gl-yziquel** [TornaxO7/PornOS#30]
Hi.

Nice to see a tentative learning OS in rust. Bookmarked.

However, it does not build out of the box. And an unresolved import suggests something missing...

```console
mini-me@virtucon ~/h/c/PornOS (main) [101]> cargo run
   Compiling pornos v0.1.0 (/mini-me/virtucon/home/cellar/PornOS)                         
error[E0432]: unresolved import `limine::LimineHhdmRequest`
 --> src/memory/paging/mem_structure.rs:3:5
  |                                  
3 |     limine::LimineHhdmRequest,                                                                                     
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `LimineHhdmRequest` in the root
```

**Comment by TornaxO7** [comment]
hi! Sorry for the late reply! Hm... that's strange.
I'm currently out of time, but I'll see what the issue might be.

**Comment by TornaxO7** [comment]
By the way, congrats for the first issue :D Not gonna lie, I didn't expect that someone creates an issue and *does* actually try it out xD

**Comment by TornaxO7** [comment]
Luckily it wasn't that much to do :D It's fixed and you can run it now with `cargo run` :) Currently nothing happens but you can toy around a bit by taking a look into [`start_pornos`](https://github.com/TornaxO7/PornOS/blob/main/src/lib.rs#L39-L44) for example:
```rust
fn start_pornos() {
    x86_64::instructions::interrupts::enable();

    println!("Hello there!");
    println!("General kenobi!");
}
```
and you'll see in `stdout` the output.

**Comment by gl-yziquel** [comment]
> By the way, congrats for the first issue :D Not gonna lie, I didn't expect that someone creates an issue and _does_ actually try it out xD

Why ? I had fun building SerenityOS recently.

I'm not that much of a bare metals dude, but I do get a kick at making things work.

**Comment by TornaxO7** [comment]
> > By the way, congrats for the first issue :D Not gonna lie, I didn't expect that someone creates an issue and _does_ actually try it out xD
> 
> Why ? I had fun building SerenityOS recently.

Well, PornOS can almost do nothing and it's just a toy project, so there's currently nothing special at the project (except for it's name :D)

**Comment by gl-yziquel** [comment]
> > > By the way, congrats for the first issue :D Not gonna lie, I didn't expect that someone creates an issue and _does_ actually try it out xD
> > 
> > 
> > Why ? I had fun building SerenityOS recently.
> 
> Well, PornOS can almost do nothing and it's just a toy project, so there's currently nothing special at the project (except for it's name :D)

I value toy projects. It allowed me to dive into the rust ecosystem for on-metal development.
